'use client';

import { ArrowLeft, Download, ShieldCheck, Trash2, X } from 'lucide-react';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../../lib/api';

type Summary = { goals: number; metrics: number; assessments: number; activeShares: number; privacyDefault: string };
type DataRequest = { id: string; requestType: 'export' | 'deletion'; status: string; requestedAt: string; availableAt: string; completedAt: string | null; cancelledAt: string | null };
export function PrivacyWorkspace() {
  const [summary, setSummary] = useState<Summary>(); const [requests, setRequests] = useState<DataRequest[]>([]); const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { const [a, b] = await Promise.all([api<{ data: Summary }>('privacy/summary'), api<{ data: DataRequest[] }>('privacy/requests')]); setSummary(a.data); setRequests(b.data); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load privacy controls.'); } }, []);
  useEffect(() => {
    let active = true;
    Promise.all([api<{ data: Summary }>('privacy/summary'), api<{ data: DataRequest[] }>('privacy/requests')])
      .then(([a, b]) => { if (active) { setSummary(a.data); setRequests(b.data); } })
      .catch((error: Error) => { if (active) setMessage(error.message); });
    return () => { active = false; };
  }, []);
  async function request(type: 'export' | 'deletion') { if (type === 'deletion' && !window.confirm('Schedule permanent account deletion after a 7-day grace period? You can cancel during the grace period.')) return; try { await api('privacy/requests', { method: 'POST', body: JSON.stringify({ requestType: type }) }); setMessage(type === 'export' ? 'Export requested.' : 'Deletion scheduled with a 7-day grace period.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create request.'); } }
  async function cancel(id: string) { try { await api(`privacy/requests/${id}`, { method: 'DELETE' }); setMessage('Deletion request cancelled.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not cancel.'); } }
  return <main className="workspace-shell"><header className="workspace-header"><Link className="brand" href="/app/today"><span className="brand-mark">BH</span><span>Be Human</span></Link><div className="row-actions"><Link className="button secondary" href="/app/sharing">Sharing controls</Link><Link className="button ghost" href="/app/today"><ArrowLeft/> Today</Link></div></header><section className="workspace-intro"><p className="eyebrow">Private by default</p><h1>Your data, visible and controllable.</h1><p className="lede">Export a portable copy or schedule deletion. Household access is never implied.</p></section><section className="privacy-stats">{summary ? Object.entries({ Goals: summary.goals, 'Metric observations': summary.metrics, 'Wellbeing check-ins': summary.assessments, 'Active shares': summary.activeShares }).map(([label, value]) => <article className="panel" key={label}><strong>{value}</strong><span>{label}</span></article>) : <p>Loading your data map…</p>}</section><section className="panel privacy-actions"><div><ShieldCheck/><div><h2>Portable export</h2><p>Creates a JSON copy of your account, profile, goals, plans, observations, assessments, consents, and sharing records. It expires after seven days.</p></div><button className="button primary" onClick={() => request('export')}><Download/> Request export</button></div><div className="danger-action"><Trash2/><div><h2>Delete account</h2><p>Schedules permanent deletion after seven days. Signing back in lets you cancel during the grace period.</p></div><button className="button secondary" onClick={() => request('deletion')}>Schedule deletion</button></div></section>{message && <p className="form-message" role="status">{message}</p>}<section className="resource-list"><div className="panel-header"><div><p className="eyebrow">Request history</p><h2>Exports and deletion</h2></div></div>{requests.length === 0 ? <div className="empty-state"><p>No data requests yet.</p></div> : requests.map((item) => <article className="panel resource-row" key={item.id}><div><span className="eyebrow">{item.requestType}</span><h3>{item.status}</h3><p>Requested {new Date(item.requestedAt).toLocaleString()}</p></div><div className="row-actions">{item.requestType === 'export' && item.status === 'completed' && <a className="button small primary" href={`/api/backend/privacy/exports/${item.id}`} download><Download/> Download</a>}{item.requestType === 'deletion' && item.status === 'pending' && <button className="button small secondary" onClick={() => cancel(item.id)}><X/> Cancel</button>}</div></article>)}</section></main>;
}
