'use client';

import { Archive, ArrowLeft, CheckCircle2, Plus } from 'lucide-react';
import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '../../lib/api';

type Goal = { id: string; level: string; title: string; reason: string | null; status: string; version: number };
export function GoalsWorkspace() {
  const [goals, setGoals] = useState<Goal[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const load = useCallback(() => api<{ data: Goal[] }>('goals').then((result) => setGoals(result.data)).catch((error: Error) => setMessage(error.message)).finally(() => setLoading(false)), []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(''); const form = event.currentTarget; const data = new FormData(form); try { await api('goals', { method: 'POST', body: JSON.stringify({ title: data.get('title'), level: data.get('level'), reason: data.get('reason') || undefined }) }); form.reset(); setMessage('Goal added.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save.'); } }
  async function update(goal: Goal, status: string) { try { await api(`goals/${goal.id}`, { method: 'PATCH', body: JSON.stringify({ expectedVersion: goal.version, status }) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update.'); } }
  async function archive(goal: Goal) { try { await api(`goals/${goal.id}`, { method: 'DELETE' }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not archive.'); } }
  return <main className="workspace-shell"><header className="workspace-header"><Link className="brand" href="/app/today"><span className="brand-mark">BH</span><span>Be Human</span></Link><Link className="button ghost" href="/app/today"><ArrowLeft/> Today</Link></header><div className="workspace-grid"><section><p className="eyebrow">Direction without pressure</p><h1>Goals that can bend without breaking.</h1><p className="lede">Keep the reason, a minimum viable version, and a recovery path close to the work.</p><form className="panel resource-form" onSubmit={create}><label className="field"><span>Goal</span><input name="title" maxLength={160} required placeholder="Protect an unrushed evening" /></label><label className="field"><span>Level</span><select name="level" defaultValue="outcome"><option value="direction">Direction</option><option value="outcome">Outcome</option><option value="project">Project</option><option value="habit">Habit</option><option value="action">Action</option></select></label><label className="field"><span>Why it matters (optional)</span><textarea name="reason" rows={3} maxLength={2000} /></label><button className="button primary"><Plus/> Add goal</button></form></section><section className="resource-list" aria-live="polite"><div className="panel-header"><div><p className="eyebrow">Your goals</p><h2>Active and paused</h2></div><span className="completion">{goals.length}</span></div>{message && <p className="form-message">{message}</p>}{loading ? <p>Loading…</p> : goals.length === 0 ? <div className="empty-state"><h3>No goals yet</h3><p>Add one meaningful direction. You do not need to map your whole life.</p></div> : goals.map((goal) => <article className="panel resource-row" key={goal.id}><div><span className="eyebrow">{goal.level} · {goal.status}</span><h3>{goal.title}</h3>{goal.reason && <p>{goal.reason}</p>}</div><div className="row-actions"><button className="button small secondary" onClick={() => update(goal, goal.status === 'completed' ? 'active' : 'completed')}><CheckCircle2/>{goal.status === 'completed' ? 'Reopen' : 'Complete'}</button><button className="icon-button" aria-label={`Archive ${goal.title}`} onClick={() => archive(goal)}><Archive/></button></div></article>)}</section></div></main>;
}
