'use client';

import { ArrowLeft, Copy, Link2, Plus, ShieldCheck, Trash2, Users } from 'lucide-react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '../../lib/api';

type Household = { id: string; name: string; role: string };
type Member = { id: string; displayName: string; role: string };
type Share = { id: string; granteeUserId: string; granteeName: string; resourceType: string; permission: string };
export function SharingWorkspace() {
  const searchParams = useSearchParams();
  const [households, setHouseholds] = useState<Household[]>([]); const [shares, setShares] = useState<Share[]>([]); const [members, setMembers] = useState<Member[]>([]); const [selected, setSelected] = useState(''); const [message, setMessage] = useState(''); const [inviteLink, setInviteLink] = useState('');
  const load = useCallback(async () => { const [householdResult, shareResult] = await Promise.all([api<{ data: Household[] }>('households'), api<{ data: Share[] }>('households/sharing')]); setHouseholds(householdResult.data); setShares(shareResult.data); setSelected((current) => current || householdResult.data[0]?.id || ''); }, []);
  useEffect(() => { let active = true; Promise.all([api<{ data: Household[] }>('households'), api<{ data: Share[] }>('households/sharing')]).then(([a, b]) => { if (active) { setHouseholds(a.data); setShares(b.data); setSelected(a.data[0]?.id ?? ''); } }).catch((error: Error) => { if (active) setMessage(error.message); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!selected) return; let active = true; api<{ data: Member[] }>(`households/${selected}/members`).then((result) => { if (active) setMembers(result.data); }).catch((error: Error) => { if (active) setMessage(error.message); }); return () => { active = false; }; }, [selected]);
  async function createHousehold(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api('households', { method: 'POST', body: JSON.stringify({ name: data.get('name') }) }); form.reset(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create household.'); } }
  async function invite() { if (!selected) return; try { const result = await api<{ data: { token: string } }>(`households/${selected}/invitations`, { method: 'POST', body: JSON.stringify({ role: 'member' }) }); const link = `${window.location.origin}/app/sharing?invite=${encodeURIComponent(result.data.token)}`; setInviteLink(link); await navigator.clipboard?.writeText(link); setMessage('Invitation link created and copied. It expires in seven days.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create invitation.'); } }
  async function acceptInvite() { const token = new URLSearchParams(window.location.search).get('invite'); if (!token) return; try { await api(`households/invitations/${encodeURIComponent(token)}/accept`, { method: 'POST', body: '{}' }); history.replaceState(null, '', '/app/sharing'); setMessage('Invitation accepted.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not accept invitation.'); } }
  async function grant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); try { await api(`households/${selected}/sharing`, { method: 'POST', body: JSON.stringify({ granteeUserId: data.get('member'), resourceType: data.get('resource'), permission: data.get('permission') }) }); setMessage('Sharing permission granted.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not grant permission.'); } }
  async function revoke(id: string) { try { await api(`households/sharing/${id}`, { method: 'DELETE' }); setMessage('Permission revoked immediately.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not revoke permission.'); } }
  const hasInvite = searchParams.has('invite');
  return <main className="workspace-shell"><header className="workspace-header"><Link className="brand" href="/app/today"><span className="brand-mark">BH</span><span>Be Human</span></Link><Link className="button ghost" href="/app/privacy"><ArrowLeft/> Privacy</Link></header><section className="workspace-intro"><p className="eyebrow">Explicit, revocable access</p><h1>Household membership shares nothing by itself.</h1><p className="lede">Invite people into a household, then grant only the resource and permission they need.</p>{hasInvite && <button className="button primary" onClick={acceptInvite}><Link2/> Accept invitation</button>}</section>{message && <p className="form-message" role="status">{message}</p>}<div className="workspace-grid"><section><h2>Households</h2><form className="panel resource-form" onSubmit={createHousehold}><label className="field"><span>Name</span><input name="name" required maxLength={120} placeholder="Morgan household" /></label><button className="button primary"><Plus/> Create household</button></form>{households.length > 0 && <><label className="field sharing-picker"><span>Current household</span><select value={selected} onChange={(event) => setSelected(event.target.value)}>{households.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.role}</option>)}</select></label><button className="button secondary" onClick={invite}><Copy/> Create invitation link</button>{inviteLink && <p className="invite-link">{inviteLink}</p>}</>}</section><section className="resource-list"><div className="panel-header"><div><p className="eyebrow">Narrow grants</p><h2>Who can see what</h2></div><Users/></div>{selected && members.length > 1 && <form className="panel resource-form share-form" onSubmit={grant}><label className="field"><span>Person</span><select name="member">{members.map((member) => <option value={member.id} key={member.id}>{member.displayName} · {member.role}</option>)}</select></label><label className="field"><span>Resource</span><select name="resource"><option value="calendar">Calendar</option><option value="goal">Goals</option><option value="plan">Plans</option><option value="life_event">Life events</option></select></label><label className="field"><span>Permission</span><select name="permission"><option value="view">View</option><option value="edit">Edit</option><option value="coordinate">Coordinate</option></select></label><button className="button primary"><ShieldCheck/> Grant</button></form>}{shares.length === 0 ? <div className="empty-state"><p>No active sharing grants. This is the private default.</p></div> : shares.map((share) => <article className="panel resource-row" key={share.id}><div><span className="eyebrow">{share.resourceType}</span><h3>{share.granteeName}</h3><p>{share.permission} access</p></div><button className="button small secondary" onClick={() => revoke(share.id)}><Trash2/> Revoke</button></article>)}</section></div></main>;
}
